// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARYtXKvaV308CjjVuVKjKCedwUzZoLUh0',
    appId: '1:480734771343:web:a78594b8a8d9b3335b58fa',
    messagingSenderId: '480734771343',
    projectId: 'trasin-7da62',
    authDomain: 'trasin-7da62.firebaseapp.com',
    storageBucket: 'trasin-7da62.firebasestorage.app',
    measurementId: 'G-FCPSSRGHH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8OclkX5zIPcoDNtxOaEoHOItc497RwI',
    appId: '1:480734771343:android:9b60541a57ecfc615b58fa',
    messagingSenderId: '480734771343',
    projectId: 'trasin-7da62',
    storageBucket: 'trasin-7da62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJo5gDADo-bkj5YWeknaoNXrPCeoPIws',
    appId: '1:480734771343:ios:2cb73a8af3f00b355b58fa',
    messagingSenderId: '480734771343',
    projectId: 'trasin-7da62',
    storageBucket: 'trasin-7da62.firebasestorage.app',
    iosBundleId: 'com.example.trasin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJo5gDADo-bkj5YWeknaoNXrPCeoPIws',
    appId: '1:480734771343:ios:2cb73a8af3f00b355b58fa',
    messagingSenderId: '480734771343',
    projectId: 'trasin-7da62',
    storageBucket: 'trasin-7da62.firebasestorage.app',
    iosBundleId: 'com.example.trasin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARYtXKvaV308CjjVuVKjKCedwUzZoLUh0',
    appId: '1:480734771343:web:9ba3f4c589254c5c5b58fa',
    messagingSenderId: '480734771343',
    projectId: 'trasin-7da62',
    authDomain: 'trasin-7da62.firebaseapp.com',
    storageBucket: 'trasin-7da62.firebasestorage.app',
    measurementId: 'G-Z8MWSWF778',
  );
}
